name: "EntityLocator"
author: "Lenni0451"
version: "${version}"
main: "net.lenni0451.entitylocator.Main"
api-version: "1.21"

commands:
  entitylocator:
    description: "Show a list of all entities in a by-chunk basis"
    usage: "/entitylocator [+type|-type]..."
    permission: "entitylocator.use"
  entitydump:
    description: "Dump all entities in the world to a file"
    usage: "/entitydump"
    permission: "entitylocator.use"
  playerlocator:
    description: "Show a list of all players and nearby entities"
    usage: "/playerlocator"

permissions:
  entitylocator.use:
    description: "Permission to use the EntityLocator plugin"
    default: "op"
